package com.hack4b.model;
// Generated 2016-9-11 14:56:42 by Hibernate Tools 3.5.0.Final

/**
 * Message generated by hbm2java
 */
public class Message implements java.io.Serializable {

	private Integer id;
	private String username;
	private String email;
	private String content;
	private Boolean isAdmin;
	
	//附加
	private String authCode;

	public Message() {
	}

	public Message(String username, String email, String content, Boolean isAdmin) {
		this.username = username;
		this.email = email;
		this.content = content;
		this.isAdmin = isAdmin;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Boolean getIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(Boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

	public String getAuthCode() {
		return authCode;
	}

	public void setAuthCode(String authCode) {
		this.authCode = authCode;
	}
}
