package com.hack4b.model;
// Generated 2016-9-11 14:56:42 by Hibernate Tools 3.5.0.Final

/**
 * Settings generated by hbm2java
 */
public class Settings implements java.io.Serializable {

	private String key;
	private String value;

	public Settings() {
	}

	public Settings(String key) {
		this.key = key;
	}

	public Settings(String key, String value) {
		this.key = key;
		this.value = value;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
