package com.hack4b.model;
// Generated 2016-9-11 14:56:42 by Hibernate Tools 3.5.0.Final

/**
 * Settings generated by hbm2java
 */
public class Settings implements java.io.Serializable {

	private int id;
	private String config;
	private String value;
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getConfig() {
		return config;
	}
	public void setConfig(String config) {
		this.config = config;
	}
	public String getValue() {
		return value;
	}
	public void setValue(String value) {
		this.value = value;
	}
	
}
