-- MySQL Script generated by MySQL Workbench
-- 2016年09月11日 星期日 14时27分02秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema MessageBoard
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MessageBoard
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MessageBoard` ;
USE `MessageBoard` ;

-- -----------------------------------------------------
-- Table `MessageBoard`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MessageBoard`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `content` TEXT NULL,
  `isAdmin` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MessageBoard`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MessageBoard`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MessageBoard`.`settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MessageBoard`.`settings` (
  `key` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NULL,
  PRIMARY KEY (`key`),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
